const products = [
  {
    name: "Tropicana",
    price: 89.90,
    model: "Koło",
    imgUrl: "/img/item-tropicana.png",
    id: 'tropicana',
    recommended: true,
  },
  {
    name: "Vintage Floral",
    price: 89.90,
    model: "Chatka",
    imgUrl: "/img/item-floral.png",
    id: 'vintage-floral',
    recommended: false,
  },
  {
    name: "Morska Piana",
    price: 89.90,
    model: "Kwadrat",
    imgUrl: "/img/item-piana.png",
    id: 'morska-piana',
    recommended: true,
  },
  {
    name: "Geometric",
    price: 89.90,
    model: "Koło",
    imgUrl: "/img/item-geometric.png",
    id: 'geometric',
    recommended: false,
  },
  {
    name: "Subtle Herbs",
    price: 89.90,
    model: "Koło",
    imgUrl: "/img/item-herbs.png",
    id: 'subtle-herbs',
    recommended: false,
  },
  {
    name: "Fruity",
    price: 89.90,
    model: "Kwadrat",
    imgUrl: "/img/item-fruity.png",
    id: 'fruity',
    recommended: false,
  },
  {
    name: "Flamingo",
    price: 89.90,
    model: "Koło",
    imgUrl: "/img/item-flamingo.png",
    id: 'flamingo',
    recommended: false,
  },
  {
    name: "Darkblue floral",
    price: 89.90,
    model: "Koło",
    imgUrl: "/img/item-darkblue.png",
    id: 'darkblue-floral',
    recommended: false,
  },
  {
    name: "Galaxy",
    price: 89.90,
    model: "Kwadrat",
    imgUrl: "/img/item-galaxy.png",
    id: 'galaxy',
    recommended: false,
  },
  {
    name: "Princess Dream",
    price: 89.90,
    model: "Koło",
    imgUrl: "/img/item-princess.png",
    id: 'princess-dream',
    recommended: true,
  },
  {
    name: "Zorba",
    price: 89.90,
    model: "Kwadrat",
    imgUrl: "/img/item-zorba.png",
    id: 'zorba',
    recommended: true,
  },
];

export default products;
